REGISTER_DECO(Loop)
REGISTER_DECO(RandomLoop)
REGISTER_DECO(Random)
REGISTER_DECO(IsBlackboardBoolTrue)
REGISTER_DECO(CompareBlackboardFloat)
REGISTER_DECO(CompareBlackboardInt)
REGISTER_DECO(IsBlackboardKeyValid)
REGISTER_DECO(PlayerInSight)
REGISTER_DECO(HealthPercent)

REGISTER_DECO(Success)
REGISTER_DECO(Failure)
REGISTER_DECO(Timer)
REGISTER_DECO(Cooldown)
REGISTER_DECO(GlobalCooldown)
